### PR TITLE
add support for --env and --env-file, as well as --clearenv, to preve…

### PR DESCRIPTION
**Pull request by dmjacobsen**
add support for --env and --env-file, as well as --clearenv, to prevent the external environment from showing up

### CODE REVIEW

**Comment by dmjacobsen** [comment]
I still need to add some unittests for the updates to shifter_setupenv, especially the env-file bit.

Also, there is an implicit restriction that the env-file needs to have the same path in both the external and container environment.  I'm thinking of modifying this to have shifter read the env-file in the external environment, but that will be slightly complicated by needing to ensure we are using the user's prilvileges when reading the file.

**Comment by scanon** [comment]
Would this support multiple -e options?  

shifter -e FOO=1 -e BAR=1 ...

**Comment by dmjacobsen** [comment]
yes, multiple -e options are supported

**Comment by dmjacobsen** [comment]
merging this based on discussion with @scanon

**Pull request merged**
