### PR TITLE
MPI support

### PR DESCRIPTION
**Pull request by rukkal**
This PR adds MPI support to Shifter.

The user can activate the MPI support either through the **--mpi** CLI option of Shifter:
```
srun -N 2 shifter --mpi --image=ethcscs/dockerfiles:osu5.3.2-mpich3.1.4 /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
```
or through the **--shifter-mpi** CLI option of the Slurm plugin:
```
salloc -N 2 --shifter-mpi --image=ethcscs/dockerfiles:osu5.3.2-mpich3.1.4
srun shifter /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
```

## How the MPI support works
In order to activate MPI support the compute node must provide an MPI implementation that is MPICH ABI compatible ([MPICH ABI compatibility initiative](https://www.mpich.org/abi/)) and the container's application must dynamically link to an MPI library that is also MPICH ABI compatible. We could successfully run MPI applications in containers with MPICH 3.1.4, MVAPICH2 2.2, and Intel MPI Library 2017 Update 1.

The system administrator must specify the location of the compute nodes' MPI libraries through the **siteMPISharedLibs** parameter in udiRoot.conf. The MPI dependency libraries, i.e. those libraries that the MPI libraries need to access, are configured through the **siteMPIDependencyLibs** parameter.

Shifter performs the following steps when the user requires the activation of the MPI support:
1. Searches the MPI shared libraries in the container through the container's ldconfig.
2. Compares the version numbers in the library filenames to check for ABI compatibility between compute node and container.
3. Bind mounts the compute node's MPI shared libraries on top of the containers' ones.
4. Bind mounts the compute node's dependency libraries into the container and updates the container's LD_LIBRARY_PATH accordingly.

## Other addition in the PR
We also implemented the Shifter's **--version** CLI option:
```
$shifter --version
Shifter 17.04.00
```

### CODE REVIEW

**Comment by dmjacobsen** [comment]
I'll have to look at this, the mpich abi support is fully supported by
shifter without modifications, ie following the mpi guide and using the
existing optUdiImage support.


On Apr 28, 2017 7:01 AM, "Kean Mariotti" <notifications@github.com> wrote:

This PR adds MPI support to Shifter.

The user can activate the MPI support either through the *--mpi* CLI option
of Shifter:

srun -N 2 shifter --mpi
--image=ethcscs/dockerfiles:osu5.3.2-mpich3.1.4
/usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency

or through the *--shifter-mpi* CLI option of the Slurm plugin:

salloc -N 2 --shifter-mpi --image=ethcscs/dockerfiles:osu5.3.2-mpich3.1.4
srun shifter /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency

How the MPI support works

In order to activate MPI support the compute node must provide an MPI
implementation that is MPICH ABI compatible (MPICH ABI compatibility
initiative <https://www.mpich.org/abi/>) and the container's application
must dynamically link to an MPI library that is also MPICH ABI compatible.
We could successfully run MPI applications in containers with MPICH 3.1.4,
MVAPICH2 2.2, and Intel MPI Library 2017 Update 1.

The system administrator must specify the location of the compute nodes'
MPI libraries through the *siteMPISharedLibs* parameter in udiRoot.conf.
The MPI dependency libraries, i.e. those libraries that the MPI libraries
need to access, are configured through the *siteMPIDependencyLibs*
parameter.

Shifter performs the following steps when the user requires the activation
of the MPI support:

   1. Searches the MPI shared libraries in the container through the
   container's ldconfig.
   2. Compares the version numbers in the library filenames to check for
   ABI compatibility between compute node and container.
   3. Bind mounts the compute node's MPI shared libraries on top of the
   containers' ones.
   4. Bind mounts the compute node's dependency libraries into the
   container and updates the container's LD_LIBRARY_PATH accordingly.

Other addition in the PR

We also implemented the Shifter's *--version* CLI option:

$shifter --version
Shifter 17.04.00

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/NERSC/shifter/pull/172
Commit Summary

   - first quick and dirty implementation of MPI support
   - README: added "how to run an MPI job"
   - Merge branch 'cscs' into mpi_support
   - removed hackish prototype mpi-support-hook.sh
   - added activate_mpi_support.sh
   - mpi support: added inspection of container's ld.so.cache
   - added quick-and-dirty MPI support hook
   - mpi_support: added check for dependencies in container image
   - mpi support: implemented used interface
   - mpi support: added checks for siteResources config
   - added function shifter_setupenv_site_resources
   - mpi support: got rid of hard-coded values in activate_mpi_support.sh
   - fixed GPU support integration test
   - mpi support: added configuration instructions to bash script
   - mpi support: check that container has MPI libraries
   - mpi support: changed overriding of container's MPI libraries
   - mpi support: enabled verbose output
   - gpu support integration test: minor refactoring
   - mpi support: minor refactorings in bash script
   - mpi support: added integration test
   - mpi support: fixed integration test
   - mpi support: got rid of debug output in integration test
   - mpi support: removed dead code in bash script
   - mpi support: avoid duplicated bind mounts
   - Merge branch 'master' into cscs
   - mpi support: deleted early prototype of mpi support
   - mpi support: minor renaming
   - mpi support: removed dead code in integration test
   - mpi support: added checks in integration test
   - mpi support: got rid of dead code in integration test
   - mpi support: made changes requested during code review
   - Merge branch 'mpi_support' into 'cscs'
   - removed gitlab files for pull request to NERSC
   - Merge branch 'gpu_support' into mpi_support
   - mpi support: factored out MPI support code
   - refactored utility functions
   - implemented check for site resources' folder existence
   - readded .gitlab.yml
   - fixed site resources path in integration tests
   - Merge branch 'mpi_support' into cscs
   - Merge branch 'gpu_support' into cscs
   - Added command line option to shifter to print version string
   - Added documentation page with required permissions for installation
   and execution
   - Renamed maunualinstallgpu.rst to manualinstall.rst
   - manualinstall.rst: added known issue of CLE
   - Merge branch 'master' into cscs
   - MPI support script: use "readlink" instead of "realpath"
   - MPI support script: less strict regex for library names
   - MPI support script: fixed ABI compatibiliy check
   - MPI support script: updated site libraries for Greina
   - MPI support script: added error message
   - MPI support script: added some dependencies for Greina
   - Merge branch 'mpi_support_fix' into 'cscs'
   - Merge branch 'documented_known_cle_issue' into 'cscs'
   - Moved site-specific MPI support info from bash script to udiRoot.conf
   - Fixed MPI support script
   - Changed siteMPISharedLibs from list of key-value pairs to list of full
   paths
   - Updated manual installation doc page
   - Removed parameter siteMPIBins
   - Fixed CI tests for MPI support
   - Version bump
   - Mount of siteFs: fixed mkdir
   - MR discussion fixes
   - Merge branch 'nersc_master' into cscs
   - Ensure that undefined optional MPI arguments are not dereferenced and
   passed to the bash script
   - Removed unneeded GPU-support binaries
   - Removed load of nvidia-uvm from GPU support script
   - Removed unneeded nvidia binaries from expected test results
   - Corrected documentation about native MPI configuration on Cray
   - bindImageIntoUDI: warn when image's file/folders are overridden
   - Added warnings about siteFs effects on Sphinx documentation manual
   install page
   - bindImageIntoUDI: filtered some warnings about skipped mounts
   - bindImageIntoUDI: cleaned filtering of warnings
   - ImageGW: increased sleep times to fix tests
   - Merge branch 'fix_build_after_imagegw_changes' into 'cscs'
   - Merge branch 'cleaned_filtering_of_warnings' into 'cscs'
   - test_mpi_support.py: switched to ethcscs/dockerfiles
   - Merge branch 'fixed_mpi_support_integration_tests' into 'cscs'
   - mpi support: handle empty MPI configuration options
   - mpi support: removed udiRoot.conf's "siteMPIConfigurationFiles"
   - mpi support: fixed integration test
   - mpi support: fixed integration test
   - mpi support: improved error messages
   - mpi support: updated doc/install/manuallinstall.rst
   - slurm plugin: updated Makefile
   - slurm plugin: updated unit tests' udiRoot.conf
   - Merge branch 'master' into mpi_support
   - mpi support: fixed error message
   - mpi support: added validation of site resources folder
   - mpi support: integrated with slurm plugin
   - removed dead code
   - Revert "slurm plugin: updated unit tests' udiRoot.conf"
   - Revert "Removed unneeded GPU-support binaries"
   - Revert "Removed load of nvidia-uvm from GPU support script"
   - Revert "Removed unneeded nvidia binaries from expected test results"
   - Revert "bindImageIntoUDI: cleaned filtering of warnings"
   - Revert "bindImageIntoUDI: filtered some warnings about skipped mounts"
   - Revert "Added warnings about siteFs effects on Sphinx documentation
   manual install page"
   - Revert "bindImageIntoUDI: warn when image's file/folders are
   overridden"
   - Revert "Mount of siteFs: fixed mkdir"
   - Revert "Version bump"
   - mpi support: encapsulated configurations in mpi struct
   - Merge branch 'refactor_mpi_support_configurations' into 'mpi_support'
   - Merge remote-tracking branch 'nersc/master' into mpi_support
   - mpi support: fixed error handling
   - removed .gitlab-ci.yml
   - Revert "ImageGW: increased sleep times to fix tests"
   - Revert "Added documentation page with required permissions for
   installation and execution"

File Changes

   - *M* doc/index.rst
   <https://github.com/NERSC/shifter/pull/172/files#diff-0> (2)
   - *R* doc/install/manualinstall.rst
   <https://github.com/NERSC/shifter/pull/172/files#diff-1> (57)
   - *A* extra/CI/integration/test_mpi_support.py
   <https://github.com/NERSC/shifter/pull/172/files#diff-2> (235)
   - *M* extra/CI/integration_test.sh
   <https://github.com/NERSC/shifter/pull/172/files#diff-3> (3)
   - *M* extra/Makefile.am
   <https://github.com/NERSC/shifter/pull/172/files#diff-4> (3)
   - *M* src/Makefile.am
   <https://github.com/NERSC/shifter/pull/172/files#diff-5> (21)
   - *M* src/UdiRootConfig.c
   <https://github.com/NERSC/shifter/pull/172/files#diff-6> (6)
   - *M* src/UdiRootConfig.h
   <https://github.com/NERSC/shifter/pull/172/files#diff-7> (5)
   - *A* src/activate_mpi_support.sh
   <https://github.com/NERSC/shifter/pull/172/files#diff-8> (255)
   - *A* src/mpi_support.c
   <https://github.com/NERSC/shifter/pull/172/files#diff-9> (76)
   - *A* src/mpi_support.h
   <https://github.com/NERSC/shifter/pull/172/files#diff-10> (42)
   - *M* src/setupRoot.c
   <https://github.com/NERSC/shifter/pull/172/files#diff-11> (14)
   - *M* src/shifter.c
   <https://github.com/NERSC/shifter/pull/172/files#diff-12> (19)
   - *M* src/shifter_core.c
   <https://github.com/NERSC/shifter/pull/172/files#diff-13> (6)
   - *M* src/shifter_core.h
   <https://github.com/NERSC/shifter/pull/172/files#diff-14> (1)
   - *M* src/test/Makefile.am
   <https://github.com/NERSC/shifter/pull/172/files#diff-15> (16)
   - *M* src/test/test_shifter_core.cpp
   <https://github.com/NERSC/shifter/pull/172/files#diff-16> (26)
   - *M* udiRoot.conf.example.in
   <https://github.com/NERSC/shifter/pull/172/files#diff-17> (34)
   - *M* wlm_integration/slurm/Makefile.am
   <https://github.com/NERSC/shifter/pull/172/files#diff-18> (3)
   - *M* wlm_integration/slurm/shifterSpank.c
   <https://github.com/NERSC/shifter/pull/172/files#diff-19> (22)
   - *M* wlm_integration/slurm/shifterSpank.h
   <https://github.com/NERSC/shifter/pull/172/files#diff-20> (4)
   - *M* wlm_integration/slurm/test/Makefile.am
   <https://github.com/NERSC/shifter/pull/172/files#diff-21> (16)
   - *M* wlm_integration/slurm/wrapper.c
   <https://github.com/NERSC/shifter/pull/172/files#diff-22> (6)

Patch Links:

   - https://github.com/NERSC/shifter/pull/172.patch
   - https://github.com/NERSC/shifter/pull/172.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NERSC/shifter/pull/172>, or mute the thread

**Comment by rukkal** [comment]
Hi,
with this commit [f68f974](https://github.com/NERSC/shifter/pull/172/commits/f68f97450406fbe91811ac4701fb21cda4e48251) Shifter uses only the host's ldconfig binary and doesn't touch the container's one anymore.

**Comment by scanon** [comment]
I don't think that is the behavior we want. There will likely be cases where the host and container glibc versions are too far apart.

**Comment by fcruzcscs** [comment]
@scanon Can you elaborate on the problem? it seems to me that glibc between host and container is not an issue.

If you, look at line 204 of src/activate_mpi_support.sh on [f68f974](https://github.com/NERSC/shifter/pull/172/commits/f68f97450406fbe91811ac4701fb21cda4e48251) what is being done is that the host uses its own ldconfig, sed, and readlink binaries this is still prior to the chroot so there is no glibc mix.

Note that ldconfig is using the -r option so as that ldconfig does the search on the standard locations but on the container filesystem.

**Comment by dmjacobsen** [comment]
this mechanism is not going to be integrated in based on other discussions.  I've added on the dev branch the initial modules support, which should allow for functionality-specific, site-definable, user-selectable "modules" to be implemented that can integrate the type of features you are looking for here.  The dev branch should be promoted to master within a day or so

**Comment by scanon** [comment]
I'm closing this out because it is deprecated with the support of modules

**Pull request closed without merging**
