### PR TITLE
Make the siteResource parameter optional

### PR DESCRIPTION
**Pull request by scanon**
I would like to make the siteResource parameter optional so that sites that upgrade aren't forced to update their config files.  Please review this and make sure I didn't make any bad assumptions.

### CODE REVIEW

**Comment by rukkal** [comment]
Hi Shane, thank you for giving us the opportunity to review the pull request. I have the following comments:
- I reproduced the GCC problem on CentOS 6 and I was able to solve it by rewriting two lines of code, without moving the definition of "struct gpu_support_config" around. Please have a look at [this commit](https://github.com/rukkal/shifter/commit/64a530bc99f9d78bdb7c7bd6ff2263aa536fbd9c).
- With this pull request Shifter would segfault when the user asks to activate the GPU support, but no "siteResources" have been configured. Please have a look at [this commit](https://github.com/rukkal/shifter/commit/89b01e785fe76fb9a62b0ae3b5c004c2953d5eb1) for a possible fix.

I pushed the two commits mentioned above on my ["siteoptional" branch](https://github.com/rukkal/shifter/commits/siteoptional). Basically it is your branch with the modifications that I propose.

**Comment by scanon** [comment]
@rukkal let's close this PR out and you issue a new one against your branch and I will merge it. You caught the issue I was worried about which was a null pointer but I couldn't figure out how to trigger it.

**Comment by rukkal** [comment]
@scanon Ok, I will run our test suite against my branch and then I will make the new PR.

**Comment by scanon** [comment]
Subsumed by Kean's PR

**Pull request closed without merging**
