### PR TITLE
Fix for #267

### LINKED ISSUE #267: Shifter fails to pull recent centos:8
This is due to unicode characters in the tar file header.  It looks like the only fix for this is a monkey patch to the tarfile module.

### PR DESCRIPTION
**Pull request by scanon**
This fixes #267.  It does a monkeypatch to the tarfile library.

The monkey patch as can be seen is from Vincent Batts.

### CODE REVIEW

**Comment by dmjacobsen** [comment]
i'm trying to understand this;  do we really want to extract files with xattrs?  is there a way to simply squash whatever xattrs there might be?

**Comment by scanon** [comment]
I don't think this changes the behavior of the extraction.  The issue is the tarfile barfs on the unicode encoded headers which means we can pull some newer images.

**Comment by dmjacobsen** [comment]
right, i think i understood that from the code;  i'm more wondering if the code should be deleting the xattrs instead of fixing them

**Comment by dmjacobsen** [comment]
perhaps ALL the xattrs; it's unclear what value they generate in the shifter model of execution

**Pull request merged**
