### PR TITLE
Added GPU support

### PR DESCRIPTION
**Pull request by rukkal**
This PR adds GPU support for Shifter. This PR superseeds the previous one that we did in November.

The user interface has changed since the last PR. Now to select one or more GPU devices to be made available inside the container, the user has to set the environment variable CUDA_VISIBLE_DEVICES. The value of CUDA_VISIBLE_DEVICES should be a comma separated list of GPU device IDs. E.g.:

```
CUDA_VISIBLE_DEVICES=0,2 shifter --image=cuda-samples:latest ./deviceQuery
```

When using the SLURM Workload Manager, CUDA_VISIBLE_DEVICES is always exported, and the user can control the selected GPU devices through the Generic Resource Scheduling, e.g.:
```
srun --gres=gpu:<NumGPUsPerNode>
```
Thus, Shifter can transparently support GPUs selected by the SLURM GRES plugin.

CUDA toolkit **must** be installed inside the image.

## How it works
When GPU support is requested, Shifter executes the `activate_gpu_support.sh` bash script. The script bind mounts available NVIDIA host libraries and binary utilities to the container. The container environment is also updated appropriately (updating `PATH` and `LD_LIBRARY_PATH`).

A new parameter inside `udiRoot.conf` called `siteResources` allows the user to indicate an absolute path to where site-specific (host) resources will be bind-mounted in the container.
The `_UdiRootConfig` structure has been updated accordingly.

A full list of the bind mounted site resources can be retrieved at runtime by adding the --verbose command line option. E.g.:

```
CUDA_VISIBLE_DEVICES=0,2 shifter --verbose --image=cuda-samples:latest ./deviceQuery
```

## Device numbering
The GPU devices exposed inside the container have been verified to be available to CUDA applications with device numbering starting from 0, regardless of the actual device IDs present in CUDA_VISIBLE_DEVICES. E.g. if CUDA_VISIBLE_DEVICES is 2, a CUDA application will still be able to access that GPU as device 0). This means it is possible to transparently use containers requiring a single GPU on multi-GPU nodes.

## Other additions
* Updated Shifter's help/usage message.
* Added documentation on Manual installation of Shifter with GPU support
* Added unit tests and integration tests for the new feature

### CODE REVIEW

**Comment by dmjacobsen** [comment]
OK, this sounds good.  I'll start reviewing tomorrow morning

**Comment by dmjacobsen** [comment]
Hello,

Would it be possible to move the struct gpu_support_config * pointer into UdiRootConfig?  That way the function arguments don't need to be extended with another configuration data structure.  I'd like to try to consolidate the state-configuration, as much as possible, to within the UdiRootConfig data structure to keep code maintenance simpler.  Is there a reason you would like to keep it out of the config?

Thanks,
Doug

**Comment by rukkal** [comment]
Hello Doug,

I see your point to group all the configurations in order to easily pass them around and keep the function calls clean. I will move the struct gpu_support_config into UdiRootConfig. I will update the pull request in the next few days.

Have a great weekend
Kean

**Comment by rukkal** [comment]
Hello Doug,
I pushed the changes that you requested.
Kean

**Comment by scanon** [comment]
@dmjacobsen Have you had a chance to review the update?

**Comment by lichinka** [comment]
Hello,
is there any update about this pull request?
@dmjacobsen Let me know if we can help you with anything.

Lucas

**Comment by dmjacobsen** [comment]
I'll merge this.  We may start extending some of these interfaces to do some of the other planned updates for the next release.

**Pull request merged**
