### PR TITLE
Wired up the authentication

### PR DESCRIPTION
**Pull request by cfenoy**

### CODE REVIEW

**Comment by scanon** [comment]
Carles,

Thanks for contributing this.  I've been meaning to make time for this and just haven't managed to get around to it.  If would be good if we had some tests for this.  I'm not quite sure how to handle that since we don't want to put credentials into the code.  Perhaps we could set an environment variable and if it is set, the tests would get run.  Could you take a stab at adding some tests using this approach or something else if you have any ideas?

**Comment by scanon** [comment]
@cfenoy One other reason we had held off on this is that images would still be usable by anyone on a shared system.  The plan was to also populate ACL records that would be enforced by the shifter binary.  Perhaps we could add some warning when the user first logs in until we get ACLs implemented.  @dmjacobsen What do you think?

**Comment by cfenoy** [comment]
@scanon We currently do not have the need to restrict the access to the images added to shifter, but we have an internal registry with authentication. That is why we need this. I agree this may cause some false sensation of security to the users, so I may be good to add a warning to the users at the time of the login to a registry. Once the ACLs support is in place the warning can be removed. Do you want me to add the warning?

**Comment by scanon** [comment]
@cfenoy Sorry for not merging this.  I'm actually working on wiring in the rest of the ACLs now.  I may merge your changes in with that.  Thanks again.

**Comment by scanon** [comment]
@cfenoy I hand merged these into the ACL PR that was recently merged. So I'm going to close out this PR.  Thanks for the contribution.

**Pull request closed without merging**
